security:
    providers:
        admin_users:
            memory:
                users:
                    admin: { password: '$2y$12$EWtjIw93yhNHU8.UyXoFfOgjwFaCnVaRA0cwIa1dMXqYecbAv.jWC', roles: ['ROLE_ADMIN'] }

    encoders:
        Symfony\Component\Security\Core\User\User: 'bcrypt'

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            anonymous: true
            pattern: ^/admin
            lazy: true
            provider: admin_users

            guard:
                authenticators:
                    - App\Security\Admin\LoginFormAuthenticator

            logout:
                path: admin logout

        main:
            anonymous: true
            lazy: true
            pattern: ^/

    access_control:
        - { path: ^/admin/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
