parameters:
    currency: '%env(CURRENCY)%'
    products_photos_path: /uploads/products
    gallery_photos_path: /uploads/gallery
    categories_photos_path: /uploads/categories

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\Admin\ProductController:
        arguments:
            - '%currency%'
            - '%products_photos_path%'

    App\Controller\Admin\CategoryController:
        arguments:
            - '%categories_photos_path%'

    App\Controller\Admin\GalleryPhotoController:
        arguments:
            - '%gallery_photos_path%'

    App\Twig\AppExtension:
        arguments:
            - '%currency%'

    App\Security\Admin\LoginFormAuthenticator:
        $userProvider: '@security.user.provider.concrete.admin_users'
